Fix build error of deprecated api (#697)
* fix: fix build error of deprecated api

Build failed on Trime procject with boost 1.83.0

This error begins on upstream librime(0d12d9037ae50346387fcce400be64d57fc41f92) and boost 1.83.0

/trime/app/src/main/jni/librime/src/rime/lever/customizer.cc:91:11: error: 'copy_file' is deprecated: Use copy_options instead of copy_option [-Werror,-Wdeprecated-declarations]

* require boost minimum 1.74

---------

Co-authored-by: Qijia Liu <liumeo@pku.edu.cn>